name: Coverage

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - run: zig build test -Doptimize=Debug
      - uses: crubalcaba/kcov-action@v1
        with:
          cli-args: "--include-pattern=src/root.zig,src/tests.zig kcov-out zig-cache/o/**/test"
